src/bubble.ts, src/bubbleSpec.ts, src/comical.ts, src/tail.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/15)
=> Support child bubbles

src/bubble.ts, src/comical.ts, stories/index.stories.ts
Also some test cases that illustrate a problem in paper.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/17)
=> Support color gradients, and add Caption bubble style

src/bubble.ts, src/bubbleSpec.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/18)
=> Add shadowOffset property and implementation

src/arcTail.ts, src/bubble.ts, src/bubbleSpec.ts, src/straightTail.ts, src/tail.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/19)
=> Support straight tails--and multiple tail types in general

src/bubble.ts, src/comical.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/21)
=> Add GetMaxLevel function

src/comical.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/22)
=> Add ability to notify client when active bubble changes

README.md
...and fix a few things that were out of date
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/24)
=> Update ReadMe to give basic instructions for using Comical

src/bubble.ts, stories/index.stories.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/20)
=> Algorithmic bubbles

src/bubble.ts, src/bubbleSpec.ts
If the bubble is in the default state for its old style, switch it to the default state for the new style
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/27)
=> Improve merging props to update default props when style changes

src/bubble.ts, src/speechBubble.ts, stories/index.stories.ts
Old one is now available as "ellipse". New one has a potentially configurable shape, though we're not exposing that yet, even through the spec mechanism.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/28)
=> Improve speech bubble shape

src/arcTail.ts, src/bubble.ts, src/straightTail.ts
Strictly, all bubbles are width 2, and all tails have the same width as their bubbles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/29)
=> Make all outlines width 2

src/arcTail.ts, src/bubble.ts, src/bubbleSpec.ts, src/comical.ts, src/tail.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/26)
=> Hide child's tail handles if tail is obscured

src/comical.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/31)
=> Add a function to determine whether anything is displayed at a point

src/bubble.ts, src/lineTail.ts, stories/index.stories.ts
Single pixel line tail with two tests in storybook. Please note that the single pixel may not be enough on some images.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/25)
=> Single pixel line tail

src/comical.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/33)
=> Fix case where it sometimes freezes

src/bubble.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/37)
=> Fix exception

src/arcTail.ts, src/speechBubble.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/34)
=> Fix 2 stories which are throwing errors

src/arcTail.ts, src/comical.ts, src/tail.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/36)
=> BL-7796 Keep handles outside content boxes

src/arcTail.ts, src/bubble.ts, src/bubbleSpec.ts, src/tail.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/38)
=> BL-7806 autoCurve

src/arcTail.ts, src/bubble.ts, src/curveTail.ts, src/tail.ts, src/thoughtBubble.ts, src/thoughtTail.ts, src/utilities.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/39)
=> Add Thought bubble (and thought tail) - BL-7844

src/arcTail.ts, src/bubble.ts, src/comical.ts, src/curveTail.ts, src/handle.ts, src/lineTail.ts, src/straightTail.ts, src/tail.ts, src/thoughtTail.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/41)
=> Make everything work when canvas is subject to transform:scale

src/arcTail.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/42)
=> Make tails a bit more pointed (BL-7863)

src/bubble.ts, src/bubbleSpec.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/43)
=> Implement outerBorderColor (BL-7853)

src/bubble.ts, src/random.ts, src/speechBubble.ts, src/thoughtBubble.ts, stories/index.stories.ts
More consistent arrangement of points around the content, and added a little randomness to make it seem more natural.
Some of the change benefits the pointed arc bubble too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/44)
=> improve thought bubble shape

src/arcTail.ts, src/bubble.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/46)
=> Fix some problems in outer borders (BL07853, BL-7887)

src/bubble.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/47)
=> no tails on exclamations (BL-7854)

src/comical.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/50)
=> Fix the canvas size when scaled (BL-7902)

src/bubble.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/51)
=> Avoid getting only part of gradient range on scaled fill shape

src/comical.ts, stories/index.stories.ts
* This will need a desktop PR to make it work too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/52)
=> BL-7908 Make sure child bubbles get parent outline

src/comical.ts
* add Comical.somethingHitArea()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/54)
=> BL-7907 DragHandle affordance

src/bubble.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/55)
=> Add hit testing for bubbles with style=none ( BL-8078)

src/bubbleSpec.ts, src/lineTail.ts
* width is already defined by default
* update comment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/58)
=> Clean up line tail

package.json, src/bubble.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/59)
=> BL-8192 implementing caption with line tail

src/arcTail.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/61)
=> Prevent over-long over-sharp tails in some browsers (BL-8332)

src/bubble.ts, src/bubbleSpec.ts, stories/index.stories.ts
* return to a better way to doing captions with line tails
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/60)
=> BL-8192 take a different approach to caption lines

src/bubble.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/63)
=> BL-8195 Fix a couple of bugs in Merge bubble props

src/bubble.ts, src/captionBubble.ts, src/comical.ts, stories/index.stories.ts
* added utility function to test if a bubble spec implies
an invisible svg
* only create svg if at least one bubble in it is not
transparent
* 'none' creates same shape as caption, but no border,
tail, shadow or background color
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/66)
=> BL-8648 Detect transparent svgs

src/bubble.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/67)
=> BL-8648 set default spec for 'none' to transparent

src/bubble.ts, src/bubbleSpec.ts, src/captionBubble.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/68)
=> Allow captions to optionally have rounded corners. (BL-8193)

src/bubble.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/72)
=> Fix hit testing of transparent bubbles (BL-8985)

package-publish.json, package.json, src/arcTail.ts, src/thoughtTail.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/73)
=> Connectors between child bubbles have constant width (BL-9082)

.vscode/extensions.json, .vscode/settings.json
* added extensions.json
* added settings.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/74)
=> BL-9268 Ensure Prettier

package-publish.json, package.json, src/arcTail.ts, src/bubble.ts, src/captionBubble.ts, src/comical.ts, src/containerData.ts, src/curveTail.ts, src/handle.ts, src/lineTail.ts, src/speechBubble.ts, src/straightTail.ts, src/tail.ts, src/thoughtBubble.ts, src/thoughtTail.ts, src/utilities.ts, stories/index.stories.ts, yarn.lock
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/76)
=> Upgrade npm dependencies (BL-8948)

package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/77)
=> paper.js version needs to be static for now

src/arcTail.ts, src/bubble.ts, src/comical.ts, src/curveTail.ts, src/lineTail.ts, src/tail.ts, stories/bubbleDrag.ts, stories/index.stories.ts
* Also added support for dragging bubbles in test code
* Original code by JT, rebased, upgraded code to use new
paper version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/78)
=> BL-8537 Support partly-transparent backgrounds

src/arcTail.ts, src/bubble.ts, src/tail.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/80)
=> Fix error when a tail is completely covered by its bubble (BL-9451)

stories/index.stories.ts
* for partly transparent Just Text box with straight tail
* no production code changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/82)
=> Add some stories and reorganize them a bit

src/comical.ts, stories/index.stories.ts
* either the parent or one of the child bubbles
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/83)
=> BL-9468 add method to remove a bubble from family

src/bubble.ts, src/circleBubble.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/84)
=> Support simple circular bubbles (BL-9318)

src/captionBubble.ts
Especially helpful when content is left-aligned
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/86)
=> Small increase in caption padding

src/comical.ts, stories/index.stories.ts
* make remaining child inherit color from deleted parent
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/91)
=> BL-10002 fix delete problem

src/comical.ts, src/handle.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/101)
=> Support dragging tail onto image overlay (BL-11184)

src/bubble.ts, src/bubbleSpec.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/103)
=> Add new style 'rectangle'

src/bubble.ts, src/captionBubble.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/104)
=> Make rectangles thinner (BL-11618)

src/bubble.ts, src/captionBubble.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/comical-js/105)
=> Restore padding for style 'none' and BG color (BL-11715)

src/comical.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/comical-js/112)
=> Don't allow getBubbleHit to find ones that are display:none

src/bubble.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/comical-js/115)
=> Make rectangle be drawn 1px black (BL-14075)

.gitignore, src/comical.ts, src/curveTail.ts, stories/index.stories.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/comical-js/116)
=> Allow tail midpoint to be dragged into elements via selector (BL-14407)
